name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NODE_ENV: ${{ secrets.NODE_ENV}}
          PORT: ${{ secrets.PORT }}
  continuous-deployment:
    needs: continous-integration
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "peaceful-retreat-65590" #Must be unique in Heroku
          heroku_email: "zhangzhikai71@gmail.com"
          procfile: "web: npm start"
